language: objective-c
osx_image: xcode8.2
script:
  - ./tests.rb
after_success:
  - bash <(curl -s https://codecov.io/bash) -J '^FringesExample$'
  - bash <(curl -s https://codecov.io/bash) -J '^SpecUIKitFringes$'
  - bash <(curl -s https://codecov.io/bash) -J '^UIKitFringes$'
