language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator10.0
script: — xcodebuild clean build -workspace TransitApp.xcworkspace -scheme TransitApp -destination "platform=iOS Simulator,name=iPhone 6S" | xcpretty
