language: objective-c
osx_image: xcode8
script:
  - carthage bootstrap --platform iOS
  - set -o pipefail && xcodebuild clean build test -scheme TransitApp -destination "platform=iOS Simulator,name=iPhone SE,OS=10.0" | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'TransitApp'
